using System.Runtime.InteropServices;

namespace ApvPlayer.FFI.LibMpv;

[StructLayout(LayoutKind.Sequential)]
public struct OpenglFbo
{
        /**
         * Framebuffer object name. This must be either a valid FBO generated by
         * glGenFramebuffers() that is complete and color-renderable, or 0. If the
         * value is 0, this refers to the OpenGL default framebuffer.
         */
        public int Fbo;

        /**
         * Valid dimensions. This must refer to the size of the framebuffer. This
         * must always be set.
         */
        public int W;

        public int H;

        /**
         * Underlying texture internal format (e.g. GL_RGBA8), or 0 if unknown. If
         * this is the default framebuffer, this can be an equivalent.
         */
        public int InternalFormat;
}